### ISSUE TITLE
Make code py3 compatible

### ISSUE THREAD

**Issue by sgratiy** [AllenInstitute/ipfx#141]
- [x] Create local test environments/workflow using tox
- [x] Using 2to3 or Futurize packages to convert test suit to Python3.7 
- [x] Convert application code to Python3.7 
- [x] Provide support for Python2.7 compatible.
- [x] Add a build stage for Python 3.7 on Bamboo
