### ISSUE TITLE
Sweep extraction module cannot find stimulus ontology file

### ISSUE THREAD

**Issue by sgratiy** [AllenInstitute/ipfx#451]
**Describe the bug**
When run sweep extraction module in the LIMS pipeline, get this error:

FileNotFoundError: [Errno 2] No such file or directory: '/allen/programs/celltypes/production/mousecelltypes/prod2684/Ephys_Roi_Result_1030100919/stimulus_ontology.json'

http://lims2/job_logs?id=1030105646

**Tasks**
- [x] Find all instances of the error (64 jobs since June 17)
- [x] Collect test data set
- [x] Reproduce the error locally
- [x] Track down where stimulus_ontology.json file is generated for each Ephys Roi Result
- [x] Make updates to take corrective action
- [x] Test it to validate
- [ ] deploy and rerun failed jobs

**To Reproduce**
Check for failed jobs on the EPHYS_NWB_STIMULUS_SUMMARY_V3_QUEUE

**Desired ontology**
Run sweep extraction executable should take in options stimulus_file_ontology parameter. If provided, then should query LIMS to generate stimulus ontology and write to file. otherwise, load up default ontology

Acceptance criteria:
- [x] LIMS stimulus summary v3 jobs run successfully using correct stimulus ontology

**Comment by NileGraddis** [comment]
Ok, what's going on here is that the feature extraction executable expects an argued stimulus ontology path to actually exist. The LIMS strategy argues a nonexistent stimulus ontology path, expecting the executable to query the LIMS database in order to generate an ontology file at the argued path. This causes the job the fail.

There are a couple of ways we could resolve this:
1. Restore the old behavior. If the executable is argued a nonexistent stimulus ontology path, it will attempt to query LIMS and write the results to that path. Upside: no LIMS changes requred. Downside: this executable is now doing multiple jobs, one of which requires an on-prem-at-AIBS-only database access.
2. Add a stimulus ontology generation stage right before feature extraction. This would call the [make_stimulus_ontology](https://github.com/AllenInstitute/ipfx/blob/master/ipfx/bin/make_stimulus_ontology.py) executable to write an up-to-date ontology json. Upside: concerns are separated. Downside: an extra pipeline stage.
3. Add stimulus ontology generation to the strategy (maybe even stick it in the input json). Upside: "serialize the LIMS representation of these data for input to a Python executable" seems pretty well-suited for a strategy. Downside: IPFX already has this functionality. We'd have to either remove [the relevant code](https://github.com/AllenInstitute/ipfx/blob/88dd2f67fd7aa8d72512cbf4211de391562e0b22/ipfx/bin/make_stimulus_ontology.py#L8) from ipfx or accept the duplication.

**Comment by NileGraddis** [comment]
OK, per discussion in slack, we are going with 3. I think we need to do the following to implement this:
- [ ] (0) there is a datafix which creates an `EphysStimulusOntology` well known file type
- [ ] (1) `EphysNwbStimulusSummaryV3Strategy` has a method which generates a stimulus ontology (as jsonable in-memory data)
- [ ] (2) `EphysNwbStimulusSummaryV3Strategy` has a method which generates a filepath of the form "{roi_result.storage_dir}/{datetime}_stimulus_ontology.json"
- [ ] (3) calling `EphysNwbStimulusSummaryV3Strategy.write_input` stores the outputs from 1 as json at the path returned by 2
- [ ] (4) calling `EphysNwbStimulusSummaryV3Strategy.get_json_data` points `stimulus_ontology_file` at the path returned by 2
- [ ] (5) calling `EphysNwbStimulusSummaryV3Strategy.write_input` creates/updates a unique `WellKnownFile` record of type 'EphysStimulusOntology' to point at the file generated by 3. This object is attached to the `EphysRoiResult` being processed
- [ ] (6) `EphysQcV3Strategy` passes the roi result's stimulus ontology path (from the well known file) to its executable
- [ ] (7) `EphysFeatureExtractionV3Strategy` passes the roi result's stimulus ontology path (from the well known file) to its executable

**Comment by NileGraddis** [comment]
see jira ticket: http://jira.corp.alleninstitute.org/browse/PBS-2340
